[package]
name = "language-api"
version = "0.1.0"
authors = ["drklee3 <derrick@dlee.dev>"]
edition = "2018"
default-run = "language-api"

[[bin]]
name = "language-client"
path = "src/client.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lingua = "1.0.3"
tonic = "0.4.0"
prost = "0.7.0"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
tokio = { version = "1.1.0", features = ["rt-multi-thread", "macros"]}
dotenv = "0.15.0"
warp = "0.3.0"
tower = "0.4.4"
hyper = "0.14.2"
futures = "0.3.12"
http-body = "0.4.0"
http = "0.2.3"

[build-dependencies]
tonic-build = "0.4"
